//! Claude Code integration — hooks, settings, and tool dispatch.

use std::path::PathBuf;

use color_eyre::eyre::Result;
use nyne::dispatch::routing::ctx::RouteCtx;
use nyne::dispatch::routing::tree::RouteTree;
use nyne::dispatch::script::ScriptEntry;
use nyne::node::Readable;
use nyne::provider::{ConflictInfo, ConflictParty, ConflictResolution};
use nyne::templates::{TemplateContent, TemplateEngine, TemplateView, serialize_view};
use nyne_macros::routes;
use serde::Serialize;

use super::names;
use super::prelude::*;
use super::util::dominant_ext;
use crate::config::CodingConfig;

/// Typed serde schemas for hook inputs and outputs.
pub mod hook_schema;
mod hooks;
mod settings;

const CLAUDE_DIR: &str = ".claude";
const SETTINGS_FILE: &str = "settings.json";
const OUTPUT_STYLE_FILE: &str = "principal-swe.md";

const SKILL_FILE: &str = "SKILL.md";
const REFERENCES_DIR: &str = "references";

/// Per-skill metadata generated by [`nyne_skills!`].
struct SkillDef {
    /// Directory name under `.claude/skills/` (e.g. `"nyne-analyze"`).
    dir: &'static str,
    /// Template engine key for `SKILL.md`.
    skill_tmpl: &'static str,
    /// `(filename, template_key)` pairs for reference documents.
    references: &'static [(&'static str, &'static str)],
}

impl SkillDef {
    fn find(dir: &str) -> Option<&'static Self> { SKILLS.iter().find(|s| s.dir == dir) }
}

/// Declares nyne skill directories from bare suffixes.
///
/// Each skill entry (e.g. `"analyze" => ["lsp-features", "git-integration"]`)
/// expands to:
/// - directory name `"nyne-analyze"`
/// - skill template `"claude/nyne-skill-analyze"` → `SKILL.md.j2`
/// - reference templates `"claude/nyne-ref-analyze-lsp-features"` →
///   `references/lsp-features.md.j2`
///
/// Generates [`SKILLS`] (array of [`SkillDef`]) and `register_skill_templates()`.
macro_rules! nyne_skills {
    ($($skill:literal => [$($ref:literal),* $(,)?]),+ $(,)?) => {
        const SKILLS: &[SkillDef] = &[
            $(SkillDef {
                dir: concat!("nyne-", $skill),
                skill_tmpl: concat!("claude/nyne-skill-", $skill),
                references: &[
                    $((
                        concat!($ref, ".md"),
                        concat!("claude/nyne-ref-", $skill, "-", $ref),
                    )),*
                ],
            }),+
        ];

        /// Register all skill templates into an existing builder.
        fn register_skill_templates(b: &mut nyne::templates::HandleBuilder) {
            $(
                b.register(
                    concat!("claude/nyne-skill-", $skill),
                    include_str!(concat!("templates/skills/nyne-", $skill, "/SKILL.md.j2")),
                );
                $(
                    b.register(
                        concat!("claude/nyne-ref-", $skill, "-", $ref),
                        include_str!(concat!(
                            "templates/skills/nyne-", $skill,
                            "/references/", $ref, ".md.j2"
                        )),
                    );
                )*
            )+
        }
    };
}

nyne_skills! {
    "analyze" => ["lsp-features", "git-integration"],
    "navigate" => ["path-patterns", "markdown-decomposition"],
    "refactor" => ["interface-changes", "diff-patterns"],
}

pub(crate) struct ClaudeProvider {
    ctx: Arc<ActivationContext>,
    routes: RouteTree<Self>,
    templates: Arc<TemplateEngine>,
}

impl ClaudeProvider {
    pub(crate) fn new(ctx: Arc<ActivationContext>) -> Self {
        let mut b = names::handle_builder();
        register_skill_templates(&mut b);
        let output_style_key = b.register("claude/output-style", include_str!("templates/output-style.md.j2"));
        let system_prompt_key = b.register("claude/system-prompt", include_str!("templates/system-prompt.md.j2"));
        let templates = b.finish();

        let settings_root = ctx.root().to_owned();
        let skill_view = SkillView {
            source_dir: ctx.root().display().to_string(),
            ext: dominant_ext(&ctx),
        };
        let style_templates = Arc::clone(&templates);
        let prompt_templates = Arc::clone(&templates);
        let prompt_ctx = Arc::clone(&ctx);

        let routes = routes!(Self, {
            ".claude" {
                file("settings.json", SettingsContent { root: settings_root.clone() }),
                "skills" => children_skills {
                    "{skill}" => children_skill_dir {
                        "references" => children_skill_references,
                    }
                }
                "output-styles" {
                    file("principal-swe.md",
                        TemplateContent::new(&style_templates, output_style_key,
                            serialize_view(skill_view.clone()))),
                }
            }
            no_emit "@" {
                "agents" {
                    "claude-code" {
                        "system-prompts" {
                            file("default.md",
                                TemplateContent::new(&prompt_templates, system_prompt_key,
                                    SystemPromptView { ctx: Arc::clone(&prompt_ctx) })),
                        }
                    }
                }
            }
        });

        Self { ctx, routes, templates }
    }

    #[expect(clippy::unused_self, reason = "route handler called as instance method")]
    fn children_skills(&self, _ctx: &RouteCtx<'_>) -> Vec<VirtualNode> {
        SKILLS.iter().map(|s| VirtualNode::directory(s.dir)).collect()
    }

    fn children_skill_dir(&self, ctx: &RouteCtx<'_>) -> Option<Vec<VirtualNode>> {
        let skill = SkillDef::find(ctx.param("skill"))?;
        let mut nodes = vec![VirtualNode::file(SKILL_FILE, self.skill_content(skill.skill_tmpl))];
        if !skill.references.is_empty() {
            nodes.push(VirtualNode::directory(REFERENCES_DIR));
        }
        Some(nodes)
    }

    fn children_skill_references(&self, ctx: &RouteCtx<'_>) -> Option<Vec<VirtualNode>> {
        let skill = SkillDef::find(ctx.param("skill"))?;
        Some(
            skill
                .references
                .iter()
                .map(|&(name, tmpl)| VirtualNode::file(name, self.skill_content(tmpl)))
                .collect(),
        )
    }

    /// Build a [`TemplateContent`] for the given skill template key.
    fn skill_content(&self, tmpl: &'static str) -> TemplateContent {
        TemplateContent::new(
            &self.templates,
            tmpl,
            serialize_view(SkillView {
                source_dir: self.ctx.root().display().to_string(),
                ext: dominant_ext(&self.ctx),
            }),
        )
    }
}

impl Provider for ClaudeProvider {
    fn id(&self) -> ProviderId { Self::PROVIDER_ID }

    fn should_activate(&self, _ctx: &ActivationContext) -> bool {
        self.ctx.get::<CodingConfig>().is_none_or(|c| c.claude.enabled)
    }

    fn on_conflict(
        self: Arc<Self>,
        ctx: &RequestContext<'_>,
        conflicts: &[ConflictInfo],
    ) -> Result<ConflictResolution> {
        // Force our virtual nodes over real files for nyne-managed paths.
        let dominated_by_real = conflicts.iter().any(|c| {
            matches!(c.party, ConflictParty::RealFile) && (c.name == SETTINGS_FILE || c.name == OUTPUT_STYLE_FILE)
        });
        if dominated_by_real {
            // Re-invoke route handlers so the virtual content wins.
            let nodes: Vec<VirtualNode> = conflicts
                .iter()
                .filter(|c| matches!(c.party, ConflictParty::RealFile))
                .filter_map(|c| self.routes.rebuild_node(&self, ctx, &c.name).transpose())
                .collect::<Result<_>>()?;
            return Ok(ConflictResolution::Force(nodes));
        }
        Ok(ConflictResolution::Yield)
    }

    fn children(self: Arc<Self>, ctx: &RequestContext<'_>) -> Nodes { self.routes.children(&self, ctx) }
}

/// Readable that layers nyne defaults, user `settings.json`, and injected hooks.
struct SettingsContent {
    root: PathBuf,
}

impl Readable for SettingsContent {
    fn read(&self, ctx: &RequestContext<'_>) -> Result<Vec<u8>> {
        let settings_path = VfsPath::new(&format!("{CLAUDE_DIR}/{SETTINGS_FILE}"))?;
        let real_json = ctx.real_fs.read(&settings_path).ok();
        settings::render_settings(real_json.as_deref(), &self.root)
    }
}

#[derive(Clone, Serialize)]
struct SkillView {
    source_dir: String,
    ext: String,
}

/// Dynamic view for system prompt — computes environment data at render time.
struct SystemPromptView {
    ctx: Arc<ActivationContext>,
}

impl TemplateView for SystemPromptView {
    fn render(&self, engine: &TemplateEngine, template: &str) -> Result<Vec<u8>> {
        let ext = dominant_ext(&self.ctx);
        let view = minijinja::context! {
            ext,
            source_dir => self.ctx.root().display().to_string(),
        };
        Ok(engine.render_bytes(template, &view))
    }
}

impl ClaudeProvider {
    pub(crate) const PROVIDER_ID: ProviderId = ProviderId::new("claude");
}

/// Script entries registered by the coding plugin on behalf of `ClaudeProvider`.
///
/// Respects both the master `claude.enabled` toggle (returns empty if disabled)
/// and individual `claude.hooks.*` toggles.
pub(crate) fn script_entries(config: &CodingConfig) -> Vec<ScriptEntry> {
    use std::sync::Arc;

    if !config.claude.enabled {
        return Vec::new();
    }

    let t = &config.claude.hooks;
    let addr = |name: &str| format!("provider.claude.{name}");
    let mut entries: Vec<ScriptEntry> = Vec::new();

    if t.pre_tool_use {
        entries.push((
            addr("pre-tool-use"),
            Arc::new(hooks::PreToolUse::new(&config.hooks.pre_tool)),
        ));
    }
    if t.post_tool_use {
        entries.push((addr("post-tool-use"), Arc::new(hooks::PostToolUse::new())));
    }
    if t.session_start {
        entries.push((addr("session-start"), Arc::new(hooks::SessionStart::new())));
    }
    if t.stop {
        entries.push((addr("stop"), Arc::new(hooks::Stop::new(&config.hooks.stop))));
    }
    if t.statusline {
        entries.push((addr("statusline"), Arc::new(hooks::Statusline)));
    }

    entries
}
