//! Claude Code integration — hooks, settings, and tool dispatch.
//!
//! Provides a virtual `.claude/` directory tree containing merged settings,
//! injected hook scripts, skill definitions, and a system prompt. The
//! provider activates only when `claude.enabled` is true in coding config.
//!
//! Hook scripts are registered via [`script_entries`] and execute as
//! [`Script`](nyne::dispatch::script::Script) trait objects — one per
//! Claude Code hook event type (pre-tool-use, post-tool-use, session-start,
//! stop, statusline).

use std::path::PathBuf;

use nyne::dispatch::routing::ctx::RouteCtx;
use nyne::dispatch::routing::tree::RouteTree;
use nyne::dispatch::script::{Script, ScriptEntry, provider_script_address};
use nyne::node::Readable;
use nyne::prelude::*;
use nyne::provider::{ConflictInfo, ConflictParty, ConflictResolution};
use nyne::templates::{TemplateEngine, serialize_view};
use nyne_macros::routes;
use nyne_source::providers::util::dominant_ext;
use nyne_source::providers::well_known as names;
use serde::Serialize;

use crate::config::Config;

/// Typed serde schemas for hook inputs and outputs.
pub mod hook_schema;
/// Claude Code hook implementations as script trait objects.
mod hooks;
/// Claude Code user settings and configuration.
mod settings;

/// Top-level `.claude` directory name.
const CLAUDE_DIR: &str = ".claude";
/// Settings file name.
const SETTINGS_FILE: &str = "settings.json";
/// Default output style file name.
const OUTPUT_STYLE_FILE: &str = "principal-swe.md";

/// Skill definition file name.
const SKILL_FILE: &str = "SKILL.md";
/// Directory name for skill reference documents.
const REFERENCES_DIR: &str = "references";

/// Per-skill metadata generated by [`nyne_skills!`].
struct SkillDef {
    /// Directory name under `.claude/skills/` (e.g. `"nyne-analyze"`).
    dir: &'static str,
    /// Template engine key for `SKILL.md`.
    skill_tmpl: &'static str,
    /// `(filename, template_key)` pairs for reference documents.
    references: &'static [(&'static str, &'static str)],
}

/// Methods for [`SkillDef`].
impl SkillDef {
    /// Find a skill definition by directory name.
    fn find(dir: &str) -> Option<&'static Self> { SKILLS.iter().find(|s| s.dir == dir) }
}

/// Declares nyne skill directories from bare suffixes.
///
/// Each skill entry (e.g. `"analyze" => ["lsp-features", "git-integration"]`)
/// expands to:
/// - directory name `"nyne-analyze"`
/// - skill template `"claude/nyne-skill-analyze"` → `SKILL.md.j2`
/// - reference templates `"claude/nyne-ref-analyze-lsp-features"` →
///   `references/lsp-features.md.j2`
///
/// Generates [`SKILLS`] (array of [`SkillDef`]) and `register_skill_templates()`.
macro_rules! nyne_skills {
    ($($skill:literal => [$($ref:literal),* $(,)?]),+ $(,)?) => {
        const SKILLS: &[SkillDef] = &[
            $(SkillDef {
                dir: concat!("nyne-", $skill),
                skill_tmpl: concat!("claude/nyne-skill-", $skill),
                references: &[
                    $((
                        concat!($ref, ".md"),
                        concat!("claude/nyne-ref-", $skill, "-", $ref),
                    )),*
                ],
            }),+
        ];

        /// Register all skill templates into an existing builder.
        fn register_skill_templates(b: &mut nyne::templates::HandleBuilder) {
            $(
                b.register(
                    concat!("claude/nyne-skill-", $skill),
                    include_str!(concat!("templates/skills/nyne-", $skill, "/SKILL.md.j2")),
                );
                $(
                    b.register(
                        concat!("claude/nyne-ref-", $skill, "-", $ref),
                        include_str!(concat!(
                            "templates/skills/nyne-", $skill,
                            "/references/", $ref, ".md.j2"
                        )),
                    );
                )*
            )+
        }
    };
}

nyne_skills! {
    "analyze" => ["lsp-features", "git-integration"],
    "navigate" => ["path-patterns", "markdown-decomposition"],
    "refactor" => ["interface-changes", "diff-patterns"],
}

/// Provider for Claude Code integration — hooks, settings, and tool dispatch.
///
/// Contributes the virtual `.claude/` directory containing `settings.json`
/// (merged from nyne defaults + user config + injected hooks), a system
/// prompt, skill directories with reference docs, and an output style file.
/// Activates only when `claude.enabled` is true; merges non-destructively
/// with any pre-existing `.claude/` directory on the real filesystem.
pub struct ClaudeProvider {
    ctx: Arc<ActivationContext>,
    config: Config,
    routes: RouteTree<Self>,
    templates: Arc<TemplateEngine>,
}

/// Methods for [`ClaudeProvider`].
impl ClaudeProvider {
    /// Create a new Claude provider, registering routes and templates.
    pub(crate) fn new(ctx: Arc<ActivationContext>, config: Config) -> Self {
        let mut b = names::handle_builder();
        register_skill_templates(&mut b);
        b.register_partial("partials/nyne-vfs", include_str!("templates/partials/nyne-vfs.md.j2"));
        b.register_partial(
            "partials/nyne-vfs-agent",
            include_str!("templates/partials/nyne-vfs-agent.md.j2"),
        );
        let output_style_key = b.register("claude/output-style", include_str!("templates/output-style.md.j2"));
        let system_prompt_key = b.register("claude/system-prompt", include_str!("templates/system-prompt.md.j2"));
        let agent_nyne_key = b.register("claude/agent-nyne", include_str!("templates/agents/nyne.md.j2"));
        let templates = b.finish();
        let settings_root = ctx.root().to_owned();
        let skill_view = SkillView {
            source_dir: ctx.root().display().to_string(),
            ext: dominant_ext(&ctx),
        };
        // Clones for routes! macro — each file() closure captures by move.
        let agent_skill_view = skill_view.clone();
        let agent_templates = Arc::clone(&templates);
        let style_templates = Arc::clone(&templates);
        let prompt_templates = Arc::clone(&templates);
        let prompt_ctx = Arc::clone(&ctx);

        let routes = routes!(Self, {
            ".claude" {
                file("settings.json", SettingsContent { root: settings_root.clone() }),
                "skills" => children_skills {
                    "{skill}" => children_skill_dir {
                        "references" => children_skill_references,
                    }
                }
                "agents" {
                    file("nyne.md",
                        TemplateContent::new(&agent_templates, agent_nyne_key,
                            serialize_view(&agent_skill_view))),
                }
                "output-styles" {
                    file("principal-swe.md",
                        TemplateContent::new(&style_templates, output_style_key,
                            serialize_view(&skill_view))),
                }
            }
            no_emit "@" {
                "agents" {
                    "claude-code" {
                        "system-prompts" {
                            file("default.md",
                                TemplateContent::new(&prompt_templates, system_prompt_key,
                                    SystemPromptView { ctx: Arc::clone(&prompt_ctx) })),
                        }
                    }
                }
            }
        });

        Self {
            ctx,
            config,
            routes,
            templates,
        }
    }

    #[expect(clippy::unused_self, reason = "route handler called as instance method")]
    /// List all registered skill directories.
    fn children_skills(&self, _ctx: &RouteCtx<'_>) -> Vec<VirtualNode> {
        SKILLS.iter().map(|s| VirtualNode::directory(s.dir)).collect()
    }

    /// List children of a skill directory (SKILL.md and references).
    fn children_skill_dir(&self, ctx: &RouteCtx<'_>) -> Option<Vec<VirtualNode>> {
        let skill = SkillDef::find(ctx.param("skill"))?;
        let mut nodes = vec![VirtualNode::file(SKILL_FILE, self.skill_content(skill.skill_tmpl))];
        if !skill.references.is_empty() {
            nodes.push(VirtualNode::directory(REFERENCES_DIR));
        }
        Some(nodes)
    }

    /// List reference document files for a skill.
    fn children_skill_references(&self, ctx: &RouteCtx<'_>) -> Option<Vec<VirtualNode>> {
        let skill = SkillDef::find(ctx.param("skill"))?;
        Some(
            skill
                .references
                .iter()
                .map(|&(name, tmpl)| VirtualNode::file(name, self.skill_content(tmpl)))
                .collect(),
        )
    }

    /// Build a [`TemplateContent`] for the given skill template key.
    fn skill_content(&self, tmpl: &'static str) -> TemplateContent {
        TemplateContent::new(
            &self.templates,
            tmpl,
            serialize_view(&SkillView {
                source_dir: self.ctx.root().display().to_string(),
                ext: dominant_ext(&self.ctx),
            }),
        )
    }
}

/// [`Provider`] implementation for [`ClaudeProvider`].
impl Provider for ClaudeProvider {
    /// Return the Claude provider identifier.
    fn id(&self) -> ProviderId { Self::PROVIDER_ID }

    /// Activate only when Claude integration is enabled in config.
    fn should_activate(&self, _ctx: &ActivationContext) -> bool { self.config.enabled }

    /// Handle conflicts by merging with existing `.claude` directories.
    fn on_conflict(
        self: Arc<Self>,
        ctx: &RequestContext<'_>,
        conflicts: &[ConflictInfo],
    ) -> Result<ConflictResolution> {
        // Force our virtual nodes over real files for nyne-managed paths.
        let dominated_by_real = conflicts.iter().any(|c| {
            matches!(c.party(), ConflictParty::RealFile) && (c.name() == SETTINGS_FILE || c.name() == OUTPUT_STYLE_FILE)
        });
        if dominated_by_real {
            // Re-invoke route handlers so the virtual content wins.
            let nodes: Vec<VirtualNode> = conflicts
                .iter()
                .filter(|c| matches!(c.party(), ConflictParty::RealFile))
                .filter_map(|c| self.routes.rebuild_node(&self, ctx, c.name()).transpose())
                .collect::<Result<_>>()?;
            return Ok(ConflictResolution::Force(nodes));
        }
        Ok(ConflictResolution::Yield)
    }

    /// Dispatch children through the route tree.
    fn children(self: Arc<Self>, ctx: &RequestContext<'_>) -> Nodes { self.routes.children(&self, ctx) }
}

/// Readable that layers nyne defaults, user `settings.json`, and injected hooks.
///
/// On read, merges three sources in priority order: nyne's built-in defaults
/// (hook entries, permissions), the user's on-disk `settings.json` (if present),
/// and dynamically injected hook scripts. The merge is non-destructive — user
/// settings are preserved and nyne entries are additive.
struct SettingsContent {
    root: PathBuf,
}

/// [`Readable`] implementation for [`SettingsContent`].
impl Readable for SettingsContent {
    /// Read merged settings layering nyne defaults, user config, and injected hooks.
    fn read(&self, ctx: &RequestContext<'_>) -> Result<Vec<u8>> {
        let settings_path = VfsPath::new(&format!("{CLAUDE_DIR}/{SETTINGS_FILE}"))?;
        let real_json = ctx.real_fs.read(&settings_path).ok();
        settings::render_settings(real_json.as_deref(), &self.root)
    }
}

#[derive(Clone, Serialize)]
/// Template view data for a skill directory listing.
struct SkillView {
    source_dir: String,
    ext: String,
}

/// Dynamic view for system prompt — computes environment data at render time.
struct SystemPromptView {
    ctx: Arc<ActivationContext>,
}

/// [`TemplateView`] implementation for [`SystemPromptView`].
impl TemplateView for SystemPromptView {
    /// Render the system prompt with environment data.
    fn render(&self, engine: &TemplateEngine, template: &str) -> Result<Vec<u8>> {
        let ext = dominant_ext(&self.ctx);
        let view = minijinja::context! {
            ext,
            source_dir => self.ctx.root().display().to_string(),
        };
        Ok(engine.render_bytes(template, &view))
    }
}

/// Provider ID constant.
impl ClaudeProvider {
    /// Unique provider identifier for Claude integration.
    pub(crate) const PROVIDER_ID: ProviderId = ProviderId::new("claude");
}

/// Script entries registered by the coding plugin on behalf of `ClaudeProvider`.
///
/// Respects both the master `claude.enabled` toggle (returns empty if disabled)
/// and individual `claude.hooks.*` toggles. Derives script names from
/// [`HOOK_REGISTRY`](settings::HOOK_REGISTRY).
pub fn script_entries(config: &Config) -> Vec<ScriptEntry> {
    use std::sync::Arc;

    if !config.enabled {
        return Vec::new();
    }

    let t = &config.hooks;
    let addr = |name| provider_script_address("claude", name);
    let mut entries: Vec<ScriptEntry> = Vec::new();

    for def in settings::HOOK_REGISTRY {
        if !match def.script_name {
            "pre-tool-use" => t.pre_tool_use,
            "post-tool-use" => t.post_tool_use,
            "session-start" => t.session_start,
            "stop" => t.stop,
            _ => continue,
        } {
            continue;
        }
        let script: Arc<dyn Script> = match def.script_name {
            "pre-tool-use" => Arc::new(hooks::PreToolUse::new(&config.hook_config.pre_tool)),
            "post-tool-use" => Arc::new(hooks::PostToolUse::new()),
            "session-start" => Arc::new(hooks::SessionStart::new()),
            "stop" => Arc::new(hooks::Stop::new(&config.hook_config.stop)),
            _ => unreachable!(),
        };
        entries.push((addr(def.script_name), script));
    }

    // Statusline is wired via `statusLine.command` in default_settings,
    // not through the hooks array — registered separately.
    if t.statusline {
        entries.push((addr("statusline"), Arc::new(hooks::Statusline)));
    }

    entries
}
