/// Per-skill metadata generated by [`nyne_skills!`].
pub(super) struct SkillDef {
    /// Directory name under `.claude/skills/` (e.g. `"nyne-analyze"`).
    pub(super) dir: &'static str,
    /// Template engine key for `SKILL.md`.
    pub(super) skill_tmpl: &'static str,
    /// `(filename, template_key)` pairs for reference documents.
    pub(super) references: &'static [(&'static str, &'static str)],
}
/// Methods for [`SkillDef`].
impl SkillDef {
    /// Find a skill definition by directory name.
    pub(super) fn find(dir: &str) -> Option<&'static Self> { SKILLS.iter().find(|s| s.dir == dir) }
}
/// Declares nyne skill directories from bare suffixes.
///
/// Each skill entry (e.g. `"analyze" => ["lsp-features", "git-integration"]`)
/// expands to:
/// - directory name `"nyne-analyze"`
/// - skill template `"claude/nyne-skill-analyze"` -> `SKILL.md.j2`
/// - reference templates `"claude/nyne-ref-analyze-lsp-features"` ->
///   `references/lsp-features.md.j2`
///
/// Generates [`SKILLS`] (array of [`SkillDef`]) and `register_skill_templates()`.
macro_rules! nyne_skills {
    ($($skill:literal => [$($ref:literal),* $(,)?]),+ $(,)?) => {
        pub(super) const SKILLS: &[SkillDef] = &[
            $(SkillDef {
                dir: concat!("nyne-", $skill),
                skill_tmpl: concat!("claude/nyne-skill-", $skill),
                references: &[
                    $((
                        concat!($ref, ".md"),
                        concat!("claude/nyne-ref-", $skill, "-", $ref),
                    )),*
                ],
            }),+
        ];

        /// Register all skill templates into an existing builder.
        pub(super) fn register_skill_templates(b: &mut nyne::templates::HandleBuilder) {
            $(
                b.register(
                    concat!("claude/nyne-skill-", $skill),
                    include_str!(concat!("templates/skills/nyne-", $skill, "/SKILL.md.j2")),
                );
                $(
                    b.register(
                        concat!("claude/nyne-ref-", $skill, "-", $ref),
                        include_str!(concat!(
                            "templates/skills/nyne-", $skill,
                            "/references/", $ref, ".md.j2"
                        )),
                    );
                )*
            )+
        }
    };
}

nyne_skills! {
    "analyze" => ["lsp-features", "git-integration"],
    "navigate" => ["path-patterns", "markdown-decomposition"],
    "refactor" => ["interface-changes", "diff-patterns"],
}
