use std::fmt;
use std::path::PathBuf;

use color_eyre::eyre::Result;

use crate::router::{Next, Request};

/// Unique identifier for a provider in the middleware chain.
///
/// Intentionally separate from [`Plugin::id`](crate::plugin::Plugin::id),
/// which identifies the *plugin* (used for config namespace lookup under
/// `[plugin.<id>]`). A single plugin may own multiple providers, each with
/// its own `ProviderId` — e.g., the LSP plugin owns both `"lsp"` and
/// `"workspace-search"` providers while its plugin ID is `"lsp"`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ProviderId(&'static str);

impl ProviderId {
    pub const fn new(name: &'static str) -> Self { Self(name) }

    pub const fn as_str(&self) -> &'static str { self.0 }
}

impl fmt::Debug for ProviderId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result { write!(f, "ProviderId({:?})", self.0) }
}

impl fmt::Display for ProviderId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result { f.write_str(self.0) }
}

/// Provider identity and ordering metadata.
///
/// Implemented by [`define_provider!`] — providers should not implement this
/// trait manually. The macro generates `PROVIDER_ID` and `DEPENDENCIES`
/// constants on the struct and implements this trait from them.
pub trait ProviderMeta {
    /// Unique identifier for this provider.
    fn id(&self) -> ProviderId;

    /// Declared dependencies — providers that must appear earlier in the chain.
    fn dependencies(&self) -> &[ProviderId] { &[] }

    /// Ordering priority within the same dependency depth tier.
    /// Lower values run first. Default is 0. Providers at the same
    /// depth and priority fall back to lexicographic ID tiebreak.
    fn priority(&self) -> i32 { 0 }

    /// Whether this provider is terminal (always last in the chain).
    /// Only one provider should return `true` — typically the real-FS provider.
    fn terminal(&self) -> bool { false }
}

/// A middleware provider in the dispatch chain.
///
/// Providers are ordered by dependency graph (topological sort) and invoked
/// in sequence for each FUSE operation. Each provider can inspect the request,
/// contribute nodes, attach capabilities, perform side effects, and continue
/// the chain via `next.run(req)`.
///
/// Identity and ordering metadata (`id`, `dependencies`, `priority`,
/// `terminal`) live on the [`ProviderMeta`] supertrait, generated by
/// [`define_provider!`]. This trait only contains the behavioral methods
/// that providers customize.
pub trait Provider: ProviderMeta + Send + Sync {
    /// Middleware entry point.
    ///
    /// Three-way control flow:
    /// - Call `next.run(req)?` then `Ok(())` — continue chain
    /// - Return `Ok(())` without calling next — chain stops, operation succeeds
    /// - Return `Err(...)` — chain stops, operation fails
    fn accept(&self, req: &mut Request, next: &Next) -> Result<()> { next.run(req) }

    /// Called when source files change (e.g., via filesystem watcher).
    ///
    /// Providers return invalidation events for derived virtual content that
    /// maps to different paths than the changed source files. The router handles
    /// invalidation for the changed paths themselves — providers only need to
    /// report *derived* invalidations (e.g., when `.git/refs/` changes, the git
    /// provider invalidates `@/git/branches/`).
    ///
    /// This is event-driven (triggered by watcher), not request-driven.
    fn on_change(&self, _changed: &[PathBuf]) -> Vec<InvalidationEvent> { Vec::new() }
}

/// A request to invalidate derived virtual content.
///
/// Returned by [`Provider::on_change`] when a source file change implies
/// that virtual content at a different path is stale.
#[derive(Debug, Clone)]
pub struct InvalidationEvent {
    /// The virtual path to invalidate.
    pub path: PathBuf,
}

/// Define provider identity, ordering metadata, and associated constants.
///
/// Generates `PROVIDER_ID` and `DEPENDENCIES` constants on the provider
/// struct and implements [`ProviderMeta`]. The `impl Provider for` block
/// only needs to contain `accept()` and/or `on_change()`.
///
/// # Examples
///
/// ```ignore
/// // No dependencies, default priority:
/// define_provider!(NyneProvider, "nyne");
///
/// // With dependencies:
/// define_provider!(SyntaxProvider, "syntax", deps: [CompanionProvider]);
///
/// // With priority override:
/// define_provider!(CacheProvider, "cache", priority: -50);
///
/// // With terminal flag:
/// define_provider!(FsProvider, "fs", terminal: true);
///
/// // Combined:
/// define_provider!(SliceProvider, "slice", priority: -100);
/// ```
#[macro_export]
macro_rules! define_provider {
    // No deps, no extras
    ($ty:ty, $id:expr $(,)?) => {
        $crate::define_provider!(@impl $ty, $id, deps: [], extras: {});
    };
    // Deps only
    ($ty:ty, $id:expr, deps: [$($dep:ty),* $(,)?] $(,)?) => {
        $crate::define_provider!(@impl $ty, $id, deps: [$($dep),*], extras: {});
    };
    // Priority only
    ($ty:ty, $id:expr, priority: $prio:expr $(,)?) => {
        $crate::define_provider!(@impl $ty, $id, deps: [], extras: {
            fn priority(&self) -> i32 { $prio }
        });
    };
    // Terminal only
    ($ty:ty, $id:expr, terminal: $term:expr $(,)?) => {
        $crate::define_provider!(@impl $ty, $id, deps: [], extras: {
            fn terminal(&self) -> bool { $term }
        });
    };
    // Internal: generate consts + ProviderMeta impl
    (@impl $ty:ty, $id:expr, deps: [$($dep:ty),*], extras: { $($extra:tt)* }) => {
        impl $ty {
            /// Provider identifier constant.
            pub const PROVIDER_ID: $crate::router::ProviderId = $crate::router::ProviderId::new($id);
            /// Declared dependency list.
            #[allow(dead_code)]
            pub const DEPENDENCIES: &[$crate::router::ProviderId] = &[$(<$dep>::PROVIDER_ID),*];
        }

        impl $crate::router::ProviderMeta for $ty {
            fn id(&self) -> $crate::router::ProviderId { Self::PROVIDER_ID }

            $crate::define_provider!(@deps $($dep),*);

            $($extra)*
        }
    };

    // Emit dependencies() override only when deps are non-empty
    (@deps $($dep:ty),+) => {
        fn dependencies(&self) -> &[$crate::router::ProviderId] { Self::DEPENDENCIES }
    };
    (@deps) => {};
}
