//! Binary entry point for the nyne CLI.
//!
//! This crate is intentionally thin -- it parses CLI arguments via [`Cli`],
//! sets up logging, and dispatches to the library-side subcommand handlers.
//! Plugin crate linkage (`use nyne_<name> as _`) is generated by `build.rs`
//! from the `[dependencies]` section so their `linkme` distributed-slice
//! entries are discovered at link time without a hand-maintained import list.

use std::{io, process};

use clap::Parser;
use color_eyre::eyre::Result;
use nyne::cli::{Cli, ExitAction};
use tracing_subscriber::EnvFilter;

// Ensure plugin crates are linked — build.rs generates `use nyne_<name> as _;`
// for each plugin dependency so their `linkme` distributed-slice entries are
// discovered at link time.
include!(concat!(env!("OUT_DIR"), "/plugin_linkage.rs"));

/// Entry point for the nyne CLI.
///
/// Sets up `color_eyre` for rich error reports, configures `tracing` based on
/// the `-v` verbosity flag, then delegates to [`Command::run`]. Commands that
/// return an exit code are forwarded to [`std::process::exit`].
///
/// The `tracing` filter defaults to warnings-only, with `-v` enabling
/// progressively more detail. `fuser::reply` is silenced at most levels
/// because its output is extremely noisy and rarely useful for debugging
/// nyne itself.
fn main() -> Result<()> {
    color_eyre::install()?;

    let cli = Cli::parse();

    tracing_subscriber::fmt()
        .with_env_filter(EnvFilter::try_from_default_env().unwrap_or_else(|_| {
            EnvFilter::new(match cli.verbose {
                0 => "warn,fuser::reply=off",
                1 => "nyne=info,fuser::reply=off",
                2 => "nyne=debug,nyne::fuse=info,fuser::reply=off",
                _ => "nyne=trace",
            })
        }))
        .with_writer(io::stderr)
        .init();

    match cli.command.run()? {
        ExitAction::Ok => Ok(()),
        ExitAction::Exit(code) => process::exit(code),
    }
}
